# Generated by Django 5.2.8 on 2025-11-15 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PaperGenerator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exam_type", models.CharField(max_length=100)),
                ("subject", models.CharField(max_length=100)),
                ("difficulty", models.CharField(max_length=100)),
            ],
        ),
    ]
