# Generated by Django 5.2.8 on 2025-11-19 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PaperGenerator", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="papergenerator",
            name="syllabus",
            field=models.TextField(blank=True, null=True),
        ),
    ]
